### ISSUE TITLE
Is there any way to not hide the http:// ?

### ISSUE THREAD

**Issue by amitchell89** [schneidmaster/react-autolink-text#13]
I'd like to have the option of not abbreviating the http when auto detecting a link.

**Comment by schneidmaster** [comment]
Not currently. I'd be happy to accept a PR to add that as an option via a prop though. 🙂

**Comment by axehomeyg** [comment]
I thought I'd just get this working since I'm in here anyway fixing a mailto: issue. 

What should the parameter name be? 
raw={true} or
bypassAbbreviation={true} ?

I'll leave it flexible in the PR.

**Comment by axehomeyg** [comment]
#15 I just called it 'raw' for now.

**Comment by schneidmaster** [comment]
Merged and published in 3.3.0
